package Wsdl2Code.WebServices.MinyanWSService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 8/27/2014 2:40:02 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class user implements KvmSerializable {
    
    public String googleId;
    public String mail;
    public String userName;
    
    public user(){}
    
    public user(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.getProperty("googleId")== null)
        {
            Object obj = soapObject.getProperty("googleId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                googleId = j.toString();
            }else if (obj!= null && obj instanceof String){
                googleId = (String) obj;
            }
        }
        if (soapObject.getProperty("mail")== null)
        {
            Object obj = soapObject.getProperty("mail");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mail = j.toString();
            }else if (obj!= null && obj instanceof String){
                mail = (String) obj;
            }
        }
        if (soapObject.getProperty("userName")== null)
        {
            Object obj = soapObject.getProperty("userName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userName = j.toString();
            }else if (obj!= null && obj instanceof String){
                userName = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return googleId;
            case 1:
                return mail;
            case 2:
                return userName;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "googleId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mail";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "userName";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
