package Wsdl2Code.WebServices.MinyanWSService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 8/27/2014 2:40:02 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
public class WS_Enums {

    public enum SoapProtocolVersion{
        	Default(0),
        	Soap11(1),
        	Soap12(2);
        
        private int code;
        
        SoapProtocolVersion(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static SoapProtocolVersion fromString(String str)
        {
            if (str.equals("Default"))
                return Default;
            if (str.equals("Soap11"))
                return Soap11;
            if (str.equals("Soap12"))
                return Soap12;
            return null;
        }
    }
    public enum prayerType{
        	SHACHARIT(0),
        	MINCHA(1),
        	ARVIT(2);
        
        private int code;
        
        prayerType(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static prayerType fromString(String str)
        {
            if (str.equals("SHACHARIT"))
                return SHACHARIT;
            if (str.equals("MINCHA"))
                return MINCHA;
            if (str.equals("ARVIT"))
                return ARVIT;
            return null;
        }
    }
    public enum day{
        	SUNDAY(0),
        	MONDAY(1),
        	TUESDAY(2),
        	WEDNESDAY(3),
        	THURSDAY(4),
        	FRIDAY(5),
        	SATURDAY(6);
        
        private int code;
        
        day(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static day fromString(String str)
        {
            if (str.equals("SUNDAY"))
                return SUNDAY;
            if (str.equals("MONDAY"))
                return MONDAY;
            if (str.equals("TUESDAY"))
                return TUESDAY;
            if (str.equals("WEDNESDAY"))
                return WEDNESDAY;
            if (str.equals("THURSDAY"))
                return THURSDAY;
            if (str.equals("FRIDAY"))
                return FRIDAY;
            if (str.equals("SATURDAY"))
                return SATURDAY;
            return null;
        }
    }
}
